#!/bin/bash
#filer

# Define directories
dir_filer=~/Documents/3ds/filer
dir_jksv=~/Documents/3ds/jksv
dir_retroarch=~/Documents/3ds/retroarch
dir_savefiles=$dir_retroarch/cores/savefiles
dir_savestates=$dir_retroarch/cores/savestates

# Menu
echo "*** Filer / JKSM / Retroarch Menu ***";
echo "[1] Exit";
echo "[2] Backup savedatafiler subfolders";
echo "[3] Backup jksv subfolders"
echo "[4] Backup retroarch subfolders";
echo -n "Select your choice: ";
read choice;

case $choice in
  1)
  echo "";
  echo "Exiting...";
  exit 0;
  ;;

  2)
  echo "";
  rm -rf $dir_filer; mkdir -vp $dir_filer;
  cp -rRv filer/* $dir_filer/;
  echo "Done!";
  ;;

  3)
  echo "";
  rm -rf $dir_jksv; mkdir -vp $dir_jksv;
  cp -rRv jksv/* $dir_jksv/;
  echo "Done!";
  ;;

  4)
  echo "";
  rm -rf $dir_retroarch; mkdir -vp $dir_savefiles $dir_savestates;
  cp -rRv retroarch/cores/savefiles/* $dir_savefiles/;
  cp -rRv retroarch/cores/savestates/* $dir_savestates/;
  echo "Done!";
  ;;

  *)
  echo "";
  echo "Invalid choice!";
  exit 1;
  ;;

esac
exit 0;
