#!/bin/bash
#filer

# Define directories
dep_filer=~/Documents/3ds/dependencies/filer
dep_retroarch=~/Documents/3ds/dependencies/retroarch
dep_savefiles=$dep_retroarch/cores/savefiles
dep_savestates=$dep_retroarch/cores/savestates

# Menu
echo "****** Filer / Retroarch Menu ******";
echo "[1] Exit";
echo "[2] Backup savedatafiler subfolders";
echo "[3] Backup retroarch subfolders";
echo -n "Select your choice: ";
read choice;

case $choice in
  1)
  echo "";
  echo "Exiting...";
  exit 0;
  ;;

  2)
  echo "";
  rm -rf $dep_filer; mkdir -vp $dep_filer;
  cp -rRv filer/* $dep_filer/;
  echo "Done!";
  ;;

  3)
  echo "";
  rm -rf $dep_retroarch; mkdir -vp $dep_savefiles $dep_savestates;
  cp -rRv retroarch/cores/savefiles/* $dep_savefiles/;
  cp -rRv retroarch/cores/savestates/* $dep_savestates/;
  echo "Done!";
  ;;

  *)
  echo "";
  echo "Invalid choice!";
  exit 1;
  ;;

esac
exit 0;
