#!/bin/bash
# hbtool

# Define local dependencies
dependencies=~/Documents/3ds/dependencies
dep_dist=~/Documents/3ds/dist
dep_a9lh=$dependencies/a9lh
dep_decrypt9wip=$dependencies/decrypt9wip
dep_cia=$dependencies/cia
dep_filer=$dependencies/filer
dep_locales=$dependencies/locales
dep_misc=$dependencies/misc
dep_retroarch=$dependencies/retroarch
dep_savefiles=$dependencies/$dep_retroarch/cores/savefiles
dep_savestates=$dependencies/$dep_retroarch/cores/savestates
dep_roms=$dependencies/roms

# Define directories
dir_src=~/src
dir_out=$dir_src/out
dir_build=$dir_src/build
dir_3ds=$dir_out/3ds
dir_cia=$dir_out/cia
dir_luma=$dir_out/luma
dir_payloads=$dir_luma/payloads
dir_d9game=$dir_out/d9game
dir_decrypt9=$dir_out/decrypt9
dir_emunand9=$dir_out/emunand9
dir_uncart=$dir_out/uncart
dir_retroarch=$dir_out/retroarch/cores

# Define url
url_latest_retroarch=http://buildbot.libretro.com/nightly/nintendo/3ds/$(date +%Y-%m-%d)_RetroArch_3dsx.7z
url_freeshop=https://github.com/Cruel/freeShop/releases/download/1.2/freeShop-1.2.cia
url_enctitlekeys=https://3ds.titlekeys.com/downloadenc
url_seeddb=https://3ds.titlekeys.com/seeddb

# Homebrew Menu
echo "";
echo "****** Homebrew Menu ******";
echo "[1] Build Luma3DS and tools";
echo "[2] Update source";
echo -n "Select your choice: ";
read choice;

case $choice in
	1)
	# Clean src directory
	rm -rf $dir_build $dir_out $dir_src/sdmc*;
	mkdir -p $dir_build $dir_out $dir_3ds $dir_cia;

	# Copy depencencies
	cp -rR $dep_dist/* $dir_build/; cp -rR $dep_cia/apps/*.cia $dir_cia/; cp -rR $dep_filer $dir_out/;
	mv $dir_build/freeShop $dir_out/; mv $dir_out/freeShop/*.cia $dir_cia/;

	# Luma3DS
	cd $dir_build/Luma3DS; mkdir -p $dir_luma;
	make clean;
	sed -i -e 's|filepath ?=|filepath ?= 3ds/Luma3DS/|g' $dir_build/Luma3DS/CakeBrah/Makefile;
	sed -i -e 's|filepath ?=|filepath ?= 3ds/Luma3DS/|g' $dir_build/Luma3DS/CakeHax/Makefile;
	make;
	mv -v $dir_build/Luma3DS/out/luma/* $dir_luma/;
	mv -v $dir_build/Luma3DS/out/arm9loaderhax.bin $dir_out/;
	mv -v $dir_build/Luma3DS/out/3ds/Luma3DS $dir_3ds/;
	mv -v $dir_build/Luma3DS/out/Luma3DS.dat $dir_3ds/Luma3DS/;
	cp -rR $dep_locales $dir_luma/;

	# arm9loaderhax-n3ds
	cd $dir_build/arm9loaderhax;
	make clean;
	sed -i -e 's|"sdmc:/arm9loaderhax.pack"|"sdmc:/3ds/arm9loaderhax-n3ds/arm9loaderhax.pack"|g' $dir_build/arm9loaderhax/payload_installer/installer/source/main.c;
	cp $dep_a9lh/delebile/* $dir_build/arm9loaderhax/data_input/;
	rm $dir_build/arm9loaderhax/data_input/otp.bin-o3ds;
	mv $dir_build/arm9loaderhax/data_input/otp.bin-n3ds $dir_build/arm9loaderhax/data_input/otp.bin;
	make;
	mv $dir_build/arm9loaderhax/data_output $dir_3ds/arm9loaderhax-n3ds;
	mv $dir_3ds/arm9loaderhax-n3ds/arm9loaderhax.bin $dir_payloads/x_arm9loaderhax-n3ds.bin;
	rm -rf $dir_build/arm9loaderhax; cp -rR $dep_dist/arm9loaderhax $dir_build/;

	# arm9loaderhax-o3ds
	cd $dir_build/arm9loaderhax;
	make clean;
	sed -i -e 's|"sdmc:/arm9loaderhax.pack"|"sdmc:/3ds/arm9loaderhax-o3ds/arm9loaderhax.pack"|g' $dir_build/arm9loaderhax/payload_installer/installer/source/main.c;
	cp $dep_a9lh/delebile/* $dir_build/arm9loaderhax/data_input/;
	rm $dir_build/arm9loaderhax/data_input/otp.bin-n3ds;
	mv $dir_build/arm9loaderhax/data_input/otp.bin-o3ds $dir_build/arm9loaderhax/data_input/otp.bin;
	make;
	mv $dir_build/arm9loaderhax/data_output $dir_3ds/arm9loaderhax-o3ds;
	mv $dir_3ds/arm9loaderhax-o3ds/arm9loaderhax.bin $dir_payloads/x_arm9loaderhax-o3ds.bin;

  	# Decrypt9WIP
	cd $dir_build/Decrypt9WIP; mkdir -p $dir_d9game $dir_decrypt9;
	make clean;
	sed -i -e 's|"/D9Game"|"/d9game"|g' $dir_build/Decrypt9WIP/source/common.h;
	sed -i -e 's|"/Decrypt9"|"/decrypt9"|g' $dir_build/Decrypt9WIP/source/common.h;
	sed -i -e 's|"Decrypt9.log"|"/decrypt9/decrypt9.log"|g' $dir_build/Decrypt9WIP/source/common.h;
	make;
	mv -v $dir_build/Decrypt9WIP/output/Decrypt9WIP.bin $dir_payloads/up_decrypt9-v$(date +%Y%m%d).bin;
	mv -v $dir_build/Decrypt9WIP/resources/d9logo.bin $dir_decrypt9/;
	cp -rR $dep_decrypt9wip/aeskeydb.bin $dir_decrypt9/; cp -rR $dep_decrypt9wip/hs-* $dir_decrypt9/;
	mv $dir_build/seeddb/seeddb.bin $dir_decrypt9/;

	# EmuNAND9
	cd $dir_build/EmuNAND9; mkdir -p $dir_emunand9;
	make clean;
	sed -i -e 's|"/EmuNAND9"|"/emunand9"|g' $dir_build/EmuNAND9/source/common.h;
	make;
	mv -v $dir_build/EmuNAND9/output/EmuNAND9.bin $dir_payloads/right_emunand9-v$(date +%Y%m%d).bin;

	# GodMode9
	cd $dir_build/GodMode9;
	make clean;
	make;
	mv -v $dir_build/GodMode9/output/GodMode9.bin $dir_payloads/left_godmode9-v$(date +%Y%m%d).bin;

	# Uncart
	cd $dir_build/uncart; mkdir -p $dir_uncart;
	make clean;
	sed -i -e 's|"/%.16s.3d%c"|"/uncart/%.16s.3d%c"|g' $dir_build/uncart/source/main.c;
	make a9lh;
	mv -v $dir_build/uncart/uncart_arm9loaderhax.bin $dir_payloads/down_uncart-v$(date +%Y%m%d).bin;

	# bannertool
	cd $dir_build/bannertool;
	make clean;
	make;

  	# FBI
	cd $dir_build/FBI;
	make clean;
	cp -v $dir_build/bannertool/output/bannertool $dir_build/FBI/buildtools/3ds/bannertool-linux64;
	rm $dir_build/FBI/buildtools/3ds/bannertool-linux32;
	make;
	mv -v $dir_build/FBI/output/FBI.cia $dir_cia/fbi-v$(date +%Y%m%d).cia;

	# ftpd
	cd $dir_build/ftpd;
	make clean;
	make;
	mkdir -p $dir_3ds/ftpd;
	mv -v $dir_build/ftpd/ftpd.3dsx $dir_3ds/ftpd/;
	mv -v $dir_build/ftpd/ftpd.smdh $dir_3ds/ftpd/;

	# hblauncher_loader
	cd $dir_build/hblauncher_loader;
	make clean;
	sed -i -e 's|"sdmc:/|"sdmc:/3ds/|g' $dir_build/hblauncher_loader/source/hblauncher_loader.c;
	make;
	mv -v $dir_build/hblauncher_loader/hblauncher_loader.cia $dir_cia/hblauncher_loader-v$(date +%Y%m%d).cia;
	cp -rR $dep_misc/hblauncherloader* $dir_3ds/; cp -rR $dep_misc/boot.3dsx $dir_3ds/h.bin;

	# Setup RetroArch 3dsx
	cd $dir_build/Retroarch; mkdir -p $dir_retroarch;
	p7zip -d $dir_build/Retroarch/*;
	mv -v $dir_build/Retroarch/3ds/catsfc_libretro $dir_3ds/;
	mv -v $dir_build/Retroarch/3ds/fceumm_libretro $dir_3ds/;
	mv -v $dir_build/Retroarch/3ds/fb_alpha_cps2_libretro $dir_3ds/;
	mv -v $dir_build/Retroarch/3ds/fb_alpha_neo_libretro $dir_3ds/;
	mv -v $dir_build/Retroarch/3ds/pocketsnes_libretro $dir_3ds/;
	cp -rR $dep_savefiles $dir_retroarch/; cp -rR $dep_savestates $dir_retroarch/; cp -rR $dep_roms $dir_out/;

	# Cleanup
	cd ~/src;
	rm -rf $dir_build; mv -v $dir_out sdmc-v$(date +%Y%m%d);
	;;

	2)
	echo "";
    	mkdir -p $dep_dist; rm -rf $dep_dist; mkdir -p $dep_dist;
    	cd $dep_dist;
    	echo "";
    	echo "Fetching Homebrew...";
    	git clone --recursive https://github.com/AuroraWright/Luma3DS.git;
	git clone --recursive https://github.com/delebile/arm9loaderhax.git;
    	git clone --recursive https://github.com/d0k3/Decrypt9WIP.git;
    	git clone --recursive https://github.com/d0k3/EmuNAND9.git;
    	git clone --recursive https://github.com/d0k3/GodMode9.git;
    	git clone --recursive https://github.com/citra-emu/uncart;
    	git clone --recursive https://github.com/J-D-K/JKSM.git;
    	git clone --recursive https://github.com/Steveice10/bannertool.git;
    	git clone --recursive https://github.com/Steveice10/FBI.git;
    	git clone --recursive https://github.com/mtheall/ftpd;
    	git clone --recursive https://github.com/yellows8/hblauncher_loader.git;
    	mkdir -p $dep_dist/Retroarch; cd $dep_dist/Retroarch; wget $url_latest_retroarch;
    	mkdir -p $dep_dist/seeddb; cd $dep_dist/seeddb; wget $url_seeddb;
    	mv $dep_dist/seeddb/seeddb $dep_dist/seeddb/seeddb.bin;
    	mkdir -p $dep_dist/freeShop; cd $dep_dist/freeShop; wget $url_freeshop; wget $url_enctitlekeys;
    	mv -v $dep_dist/freeShop/downloadenc $dep_dist/freeShop/encTitleKeys.bin;
    	echo "";
    	echo "Source updated!";
    	;;

  	*)
    	echo "";
    	echo "Invalid choice!";
    	exit 1;
    	;;
esac

exit 0;
