#!/bin/bash
# luma3ds

# Define dependencies
dep_luma3ds=~/Documents/3ds/luma3ds
dep_a9lh=~/Documents/3ds/a9lh
dep_decrypt9wip=~/Documents/3ds/decrypt9wip
dep_cia=~/Documents/3ds/cia
dep_locales=~/Documents/3ds/locales
dep_misc=~/Documents/3ds/misc
dep_filer=~/Documents/3ds/filer
dep_jksv=~/Documents/3ds/jksv
dep_roms=~/Documents/3ds/roms
dep_latest_retroarch_nightly=http://buildbot.libretro.com/nightly/nintendo/3ds/$(date +%Y-%m-%d)_RetroArch_3dsx.7z

# Define directories
dir_src=~/src
dir_out=$dir_src/out
dir_build=$dir_src/build
dir_3ds=$dir_out/3ds
dir_luma=$dir_out/luma
dir_payloads=$dir_out/payloads
dir_d9game=$dir_out/d9game
dir_decrypt9=$dir_out/decrypt9
dir_emunand9=$dir_out/emunand9
dir_uncart=$dir_out/uncart
dir_jksv=$dir_out/jksv
dir_cia=$dir_out/cia
dir_apps=$dir_cia/apps
dir_games=$dir_cia/games
dir_updates=$dir_cia/updates

# Luma3DS Menu
echo "";
echo "**** Luma3DS Menu ****";
echo "[1] Build CFW";
echo "[2] Update repository";
echo -n "Select your choice: ";
read choice;

case $choice in
	1)
	# Clean src directory
	rm -rf $dir_build $dir_out $dir_src/luma3ds*;
	mkdir -vp $dir_build $dir_out $dir_3ds $dir_luma $dir_payloads $dir_d9game $dir_decrypt9 $dir_emunand9;
	mkdir -vp $dir_uncart $dir_jksv $dir_cia $dir_apps $dir_games $dir_updates;
	cp -rR $dep_luma3ds/* $dir_build/;

	# Copy depencencies
	cp -v $dep_cia/apps/*.cia $dir_apps/;
	cp -rR $dep_filer $dir_out/;

	# Luma3DS
	cd $dir_build/Luma3DS;
	make clean;
	sed -i -e 's|"/luma/payloads"|"/payloads"|g' $dir_build/Luma3DS/source/fs.c;
	sed -i -e 's|filepath ?=|filepath ?= 3ds/Luma3DS/|g' $dir_build/Luma3DS/CakeBrah/Makefile;
	sed -i -e 's|filepath ?=|filepath ?= 3ds/Luma3DS/|g' $dir_build/Luma3DS/CakeHax/Makefile;
	make;
	mv -v $dir_build/Luma3DS/out/arm9loaderhax.bin $dir_payloads/boot.bin;
	mv -v $dir_build/Luma3DS/out/3ds/Luma3DS $dir_3ds/;
	mv -v $dir_build/Luma3DS/out/Luma3DS.dat $dir_3ds/Luma3DS/;
	cp -rR $dep_locales $dir_luma/;

	# arm9loaderhax
	cd $dir_build/arm9loaderhax;
	sed -i -e 's|"arm9loaderhax.bin"|"/payloads/boot.bin"|g' $dir_build/arm9loaderhax/payload_stage2/source/main.c
	make clean;
	make;

	# SafeA9LHInstaller
	cd $dir_build/SafeA9LHInstaller;
	make clean;
	sed -i -e 's|"a9lh/otp.bin"|"3ds/SafeA9LHInstaller/otp.bin"|g' $dir_build/SafeA9LHInstaller/source/installer.c;
	sed -i -e 's|"a9lh/secret_sector.bin"|"3ds/SafeA9LHInstaller/secret_sector.bin"|g' $dir_build/SafeA9LHInstaller/source/installer.c;
	sed -i -e 's|"a9lh/firm0.bin"|"3ds/SafeA9LHInstaller/firm0.bin"|g' $dir_build/SafeA9LHInstaller/source/installer.c;
	sed -i -e 's|"a9lh/firm1.bin"|"3ds/SafeA9LHInstaller/firm1.bin"|g' $dir_build/SafeA9LHInstaller/source/installer.c;
	sed -i -e 's|"a9lh/payload_stage1.bin"|"3ds/SafeA9LHInstaller/payload_stage1.bin"|g' $dir_build/SafeA9LHInstaller/source/installer.c;
	sed -i -e 's|"a9lh/payload_stage2.bin"|"3ds/SafeA9LHInstaller/payload_stage2.bin"|g' $dir_build/SafeA9LHInstaller/source/installer.c;
	sed -i -e 's|filepath ?=|filepath ?= 3ds/SafeA9LHInstaller/|g' $dir_build/SafeA9LHInstaller/CakeBrah/Makefile;
	sed -i -e 's|filepath ?=|filepath ?= 3ds/SafeA9LHInstaller/|g' $dir_build/SafeA9LHInstaller/CakeHax/Makefile;
	make;
	mv -v $dir_build/SafeA9LHInstaller/out/arm9loaderhax.bin $dir_payloads/x_safea9lhinstaller-v$(date +%Y%m%d).bin;
	mv -v $dir_build/SafeA9LHInstaller/out/3ds/SafeA9LHInstaller $dir_3ds/;
	mv -v $dir_build/SafeA9LHInstaller/out/SafeA9LHInstaller.dat $dir_3ds/SafeA9LHInstaller/;
	mv -v $dir_build/arm9loaderhax/out/* $dir_3ds/SafeA9LHInstaller/;
	cp -v $dep_a9lh/* $dir_3ds/SafeA9LHInstaller/;

  	# Decrypt9WIP
	cd $dir_build/Decrypt9WIP;
	make clean;
	sed -i -e 's|"/D9Game"|"/d9game"|g' $dir_build/Decrypt9WIP/source/common.h;
	sed -i -e 's|"/Decrypt9"|"/decrypt9"|g' $dir_build/Decrypt9WIP/source/common.h;
	sed -i -e 's|"Decrypt9.log"|"/decrypt9/decrypt9.log"|g' $dir_build/Decrypt9WIP/source/common.h;
	make;
	mv -v $dir_build/Decrypt9WIP/output/Decrypt9WIP.bin $dir_payloads/up_decrypt9-v$(date +%Y%m%d).bin;
	mv -v $dir_build/Decrypt9WIP/resources/d9logo.bin $dir_decrypt9/;
	cp -v $dep_decrypt9wip/aeskeydb.bin $dir_decrypt9/;
	cp -rR $dep_decrypt9wip/hs-* $dir_decrypt9/;

	# EmuNAND9
	cd $dir_build/EmuNAND9;
	make clean;
	sed -i -e 's|"/EmuNAND9"|"/emunand9"|g' $dir_build/EmuNAND9/source/common.h;
	make;
	mv -v $dir_build/EmuNAND9/output/EmuNAND9.bin $dir_payloads/right_emunand9-v$(date +%Y%m%d).bin;

	# GodMode9
	cd $dir_build/GodMode9;
	make clean;
	make;
	mv -v $dir_build/GodMode9/output/GodMode9.bin $dir_payloads/left_godmode9-v$(date +%Y%m%d).bin;

	# Uncart
	cd $dir_build/uncart;
	make clean;
	sed -i -e 's|"/%.16s.3d%c"|"/uncart/%.16s.3d%c"|g' $dir_build/uncart/source/main.c;
	make;
	mv -v $dir_build/uncart/arm9loaderhax.bin $dir_payloads/down_uncart-v$(date +%Y%m%d).bin;

	# JKSM
	cd $dir_build/JKSM;
	make clean;
	sed -i -e 's|/JKSV|/jksv|g' $dir_build/JKSM/source/log.cpp;
	sed -i -e 's|/JKSV|/jksv|g' $dir_build/JKSM/source/sys.cpp;
	sed -i -e 's|/JKSV|/jksv|g' $dir_build/JKSM/source/titles.cpp;
	sed -i -e 's|/JKSV|/jksv|g' $dir_build/JKSM/source/util.cpp;
	sed -i -e 's|/JKSV|/jksv|g' $dir_build/JKSM/source/main.cpp;
	sed -i -e 's|/JKSV|/jksv|g' $dir_build/JKSM/source/backup.cpp;
	make cia;
	cp -v $dir_build/JKSM/JKSM.cia $dir_apps/jksm-v$(date +%Y%m%d).cia;
	cp -v $dep_jksv/* $dir_jksv/;

	# bannertool
	cd $dir_build/bannertool;
	make clean;
	make;

  	# FBI
	cd $dir_build/FBI;
	make clean;
	mv -v $dir_build/bannertool/output/bannertool $dir_build/FBI/buildtools/3ds/bannertool-linux;
	make;
	mv -v $dir_build/FBI/output/FBI.cia $dir_apps/fbi-v$(date +%Y%m%d).cia;

	# ftpd
	cd $dir_build/ftpd;
	make clean;
	make;
	mkdir -v $dir_3ds/ftpd;
	cp -v $dir_build/ftpd/ftpd.3dsx $dir_3ds/ftpd/;
	cp -v $dir_build/ftpd/ftpd.smdh $dir_3ds/ftpd/;

	# hblauncher_loader
	cd $dir_build/hblauncher_loader;
	make clean;
	sed -i -e 's|"sdmc:/|"sdmc:/3ds/|g' $dir_build/hblauncher_loader/source/hblauncher_loader.c;
	make;
	mv -v $dir_build/hblauncher_loader/hblauncher_loader.cia $dir_apps/hblauncher_loader-v$(date +%Y%m%d).cia;
	cp -v $dep_misc/hblauncherloader* $dir_3ds/;
	cp -v $dep_misc/boot.3dsx $dir_3ds/h.bin;

	# Setup RetroArch 3dsx
	cd $dir_build/Retroarch;
	p7zip -d $dir_build/Retroarch/*;
	cp -rR $dir_build/Retroarch/3ds/catsfc_libretro $dir_3ds/;
	cp -rR $dir_build/Retroarch/3ds/fceumm_libretro $dir_3ds/;
	cp -rR $dir_build/Retroarch/3ds/fb_alpha_cps2_libretro $dir_3ds/;
	cp -rR $dir_build/Retroarch/3ds/fb_alpha_neo_libretro $dir_3ds/;
	mkdir -vp $dir_out/retroarch;
	cp -rR $dep_roms $dir_out/retroarch/;

	# Cleanup
	cd ~/src;
	rm -rf $dir_build; mv -v $dir_out luma3ds-v$(date +%Y%m%d);
	echo "";
	echo "Build finished! Copy the luma folder to the root of your SD card. Remove/rename the otp.bin* file located in /3ds/safea9lhinstaller/ according to the 3DS model you have.";
	;;

	2)
	echo "";
    	mkdir -vp $dep_luma3ds; rm -rf $dep_luma3ds; mkdir -vp $dep_luma3ds;
    	cd $dep_luma3ds;
    	echo "";
    	echo "Fetching Homebrew...";
    	git clone --recursive https://github.com/AuroraWright/Luma3DS.git;
    	git clone --recursive -b noscreeninit https://github.com/AuroraWright/arm9loaderhax.git
    	git clone --recursive https://github.com/AuroraWright/SafeA9LHInstaller.git
    	git clone --recursive https://github.com/d0k3/Decrypt9WIP.git;
    	git clone --recursive https://github.com/d0k3/EmuNAND9.git;
    	git clone --recursive https://github.com/d0k3/GodMode9.git;
    	git clone --recursive https://github.com/AuroraWright/uncart.git
    	git clone --recursive https://github.com/J-D-K/JKSM.git
    	git clone --recursive https://github.com/Steveice10/bannertool.git
    	git clone --recursive https://github.com/Steveice10/FBI.git;
    	git clone --recursive https://github.com/mtheall/ftpd;
    	git clone --recursive https://github.com/yellows8/hblauncher_loader.git;
    	mkdir -p $dep_luma3ds/Retroarch; cd $dep_luma3ds/Retroarch; wget $dep_latest_retroarch_nightly;
    	echo "";
    	echo "Repository updated!";
    	echo "";
    	;;

  	*)
    	echo "";
    	echo "You selected an invalid choice!";
    	exit 1;
    	;;
esac

exit 0;
