#!/bin/bash
# retroarch

# Define directories
dir_retroarch=~/Documents/3ds/retroarch
dir_savefiles=$dir_retroarch/cores/savefiles
dir_savestates=$dir_retroarch/cores/savestates

# Menu
echo "***** Retroarch Filer Menu *****";
echo "[1] Exit";
echo "[2] Backup retroarch subfolders";
echo -n "Select your choice: ";
read choice;

case $choice in
  1)
  echo "";
  echo "Exiting...";
  exit 0;
  ;;

  2)
  echo "";
  rm -rf $dir_retroarch; mkdir -vp $dir_savefiles $dir_savestates;
  cp -rRv retroarch/cores/savefiles/* $dir_savefiles/;
  cp -rRv retroarch/cores/savestates/* $dir_savestates/;
  echo "Done!";
  ;;

  *)
  echo "";
  echo "Invalid choice!";
  exit 1;
  ;;

esac
exit 0;
  
